apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1 
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: deepak8362/web  # use httpd image from docker hub
        ports:
        - containerPort: 80 # expose port 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd # match the label of the deployment
  ports:
  - protocol: TCP
    port: 80 # the port that the service exposes
    targetPort: 80 # the port that the pod exposes
  type: LoadBalancer # use a load balancer to expose the service externally

